In [1]:
import pandas as pd
import torch
import random
import numpy as np
import torch.nn.functional as F
import torch.nn as nn

In [2]:
data = pd.read_csv('portfolio.csv')
print(data)
data = torch.tensor([data["0"],data["1"],data["2"],data["3"],data["4"],data["5"],data["6"],data["7"],data["8"],data["9"],data["10"],data["11"]])
data

     0  1  2     3     4     5     6     7    8     9    10   11
0    3  5  8  0.40  0.20  0.30  0.10  0.00  0.0  0.00  0.00  0.0
1    7  3  6  0.60  0.20  0.00  0.00  0.10  0.1  0.00  0.00  0.0
2    2  7  9  0.20  0.50  0.20  0.10  0.00  0.0  0.00  0.00  0.0
3    6  5  4  0.55  0.15  0.00  0.00  0.15  0.1  0.05  0.00  0.0
4    8  2  3  0.70  0.00  0.00  0.00  0.15  0.0  0.10  0.05  0.0
..  .. .. ..   ...   ...   ...   ...   ...  ...   ...   ...  ...
252  4  2  7  0.35  0.15  0.35  0.15  0.00  0.0  0.00  0.00  0.0
253  8  6  3  0.60  0.10  0.00  0.00  0.15  0.1  0.05  0.00  0.0
254  3  1  9  0.25  0.10  0.50  0.15  0.00  0.0  0.00  0.00  0.0
255  6  8  4  0.50  0.20  0.10  0.00  0.10  0.1  0.00  0.00  0.0
256  9  3  6  0.65  0.05  0.00  0.20  0.05  0.0  0.00  0.05  0.0

[257 rows x 12 columns]


tensor([[3.0000, 7.0000, 2.0000,  ..., 3.0000, 6.0000, 9.0000],
        [5.0000, 3.0000, 7.0000,  ..., 1.0000, 8.0000, 3.0000],
        [8.0000, 6.0000, 9.0000,  ..., 9.0000, 4.0000, 6.0000],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0500],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],
       dtype=torch.float64)

In [3]:
X = data[0:3]
Y = data[3:12]

In [4]:
len(X[0])

257

In [5]:
X,Y

(tensor([[3., 7., 2., 6., 8., 4., 5., 7., 3., 6., 8., 2., 5., 7., 4., 6., 8., 3.,
          5., 7., 4., 6., 8., 2., 5., 7., 3., 6., 8., 4., 5., 7., 3., 6., 8., 2.,
          5., 7., 4., 6., 8., 3., 5., 7., 4., 6., 8., 2., 5., 7., 3., 6., 8., 4.,
          5., 7., 3., 6., 8., 2., 5., 7., 4., 6., 8., 3., 5., 7., 4., 6., 8., 2.,
          5., 7., 4., 6., 8., 3., 5., 7., 4., 6., 8., 2., 5., 7., 4., 6., 8., 3.,
          5., 7., 4., 6., 8., 2., 5., 7., 4., 6., 9., 5., 7., 3., 6., 8., 2., 4.,
          6., 8., 1., 5., 7., 4., 6., 9., 2., 5., 7., 3., 8., 4., 6., 9., 1., 5.,
          7., 4., 6., 8., 2., 5., 7., 3., 6., 9., 1., 4., 7., 5., 8., 2., 6., 9.,
          3., 5., 7., 4., 8., 1., 6., 9., 2., 5., 7., 3., 8., 4., 6., 9., 1., 5.,
          7., 4., 6., 8., 3., 5., 7., 4., 6., 9., 2., 5., 7., 3., 8., 4., 6., 9.,
          5., 7., 3., 6., 8., 2., 4., 7., 5., 9., 1., 6., 8., 4., 7., 3., 5., 8.,
          1., 6., 9., 2., 4., 7., 5., 8., 3., 6., 9., 1., 4., 7., 5., 8., 2., 6.,
          9., 3.

In [6]:
Y.shape,X.shape

(torch.Size([9, 257]), torch.Size([3, 257]))

In [7]:
Xt=[]
Yt=[]
for i in range(len(X[0])):
    tempx = ([X[0][i],X[1][i],X[2][i]])
    tempy = ([Y[0][i],Y[1][i],Y[2][i],Y[3][i],Y[4][i],Y[5][i],Y[6][i],Y[7][i],Y[8][i]])
    Xt.append(tempx)
    Yt.append(tempy)
Xt=torch.tensor(Xt)
Yt=torch.tensor(Yt)
    

In [8]:
Xt = Xt.float()
Yt=Yt.float()

In [9]:
Xt[0],Yt[0]

(tensor([3., 5., 8.]),
 tensor([0.4000, 0.2000, 0.3000, 0.1000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]))

In [10]:
xtrain = Xt[:int(0.9*len(Xt))]
ytrain = Yt[:int(0.9*len(Yt))]
xtest = Xt[int(0.9*len(Xt)):]
ytest = Yt[int(0.9*len(Yt)):]

In [11]:
ex_len = 3
n_ol = 9

bat_sz = 4
n_fl = 64
n_ml = 64
epoch = 10

head_sz = 16

In [12]:
class Reshaper(nn.Module):
    def __init__(self,n):
        self.n = n
        super(Reshaper, self).__init__()

    def forward(self, x):
        B, T, C = x.shape
        x = x.view(B, T//self.n, C*self.n)
        if x.shape[1] == 1:
            x = x.squeeze(1)
        self.out = x
        return self.out

In [13]:
modely = nn.Sequential(
    nn.Embedding(ex_len,n_fl),     #  Gets the input ([10000,8,16])
    Reshaper(2),  # becomes [10000,4,32]  # [inp_sz,blk_sz//2,emb_sz*2]
    nn.Linear(n_fl*2,n_fl),       # takes [32,200]  becomes [10000,4,200]
    nn.Tanh(),
    Reshaper(2),  # becomes [10000,2,400]   # [inp_sz,blk_sz//4,n_fl*2]
    nn.Linear(n_fl*2,n_fl),    # becomes  [10000,2,200]
    nn.Tanh(),
    Reshaper(2),  # becomes [10000,400]  # [inp_sz,n_fl*2]
    nn.Linear(n_fl*2,n_ol),    # become [400,voc_sz]
    nn.Softmax(),
)

In [14]:
optimizer = torch.optim.SGD(modely.parameters(), lr=0.001)

In [15]:
    # attention
    @torch.no_grad()
    def self_attention(x):  

        B,T,C = x.shape
        # B = 4  # block size
        # T = 8  # token (number of tokens in one example)
        # C = 32 # embedding space vector of the each one token
        # x = torch.randn(B,T,C) # example sequence
        # x -> this is how our one batch should look like here 


        # head_sz = 32# this is the splits we do of each token seqence to parellelize the sequence gen

        key = nn.Linear(C,head_sz,bias=False) # this is to make to complexities truly match  
        query =  nn.Linear(C,head_sz,bias=False) 
        value =  nn.Linear(C,head_sz,bias=False) 
        k = key(x)  # [B,T,head_sz]
        q = query(x)  # [B,T,head_sz]
        # this is -- x @ key --  then 
        # upcoming wei is the main token to token connection matrix
        wei = q @ k.transpose(-2,-1)
        # wei[0]  # TxT

        tril = torch.tril(torch.ones(T, T))  # makes a lower triangular matrix of TxT
        wei = wei.masked_fill(tril == 0, float('-inf'))
        wei = F.softmax(wei, dim=-1)

        v = value(x)
        out = wei @ v
        # out[0].shape
        return out

    # basically this is what makes up the new and improved input to the neural net

In [16]:
def embed(dim,sqz):
    a="sdjnf"

modely = nn.Sequential(

    nn.Linear(ex_len,n_fl),
    nn.ReLU(),
    nn.Linear(n_fl,n_ml), 
    # nn.Tanh(),
    nn.Linear(n_ml,n_ol),
    # nn.Softmax(),
)

ix = (torch.randperm(len(xtrain)-bat_sz))
optimizer = torch.optim.SGD(modely.parameters(), lr=0.001)

X_Train = torch.zeros([64,16,16])

In [17]:
def accuracy():
    k,d=len(xtest),len(xtest)
    for n in range(len(xtest)):
        omt = ((modely(xtest[n]))).tolist()
        # print(omt.index(max(omt)),ytest[n].item())

        k -= (omt.index(max(omt))==ytest[n].item())
    accu = (((d-k)/d) *100)
    return("Accuracy = " + str(accu))

In [18]:
for e in range(epoch):
    for i in ix:
        xt = xtrain[i:i+bat_sz]
        yt = ytrain[i:i+bat_sz]
        X_train = xt.view([bat_sz,ex_len]) #[4,784]
        Y_train = yt
        # print(X_train,Y_train)
        # break
        
        X_Train = X_Train +self_attention(X_Train)
        
        
        t = modely(X_train)
        loss = F.cross_entropy(t,Y_train) 
        optimizer.zero_grad()

        loss.backward()  # ------------
        optimizer.step()
        
        print(loss.item())
    # print(accuracy())
    if(e == int(0.8*epoch)):
        optimize = torch.optim.SGD(modely.parameters(), lr=0.0001)

2.4846816062927246
2.3898606300354004
2.2443790435791016
2.210031747817993
2.184748888015747
2.19852614402771
2.186521053314209
2.0519514083862305
2.0697391033172607
2.071556806564331
2.0510196685791016
1.9914100170135498
2.0127298831939697
1.9764820337295532
1.9523136615753174
1.8794397115707397
1.8789355754852295
1.8599205017089844
1.8282028436660767
1.825107216835022
1.7225136756896973
1.822779655456543
1.816086769104004
1.7137411832809448
1.7705732583999634
1.7599674463272095
1.7759679555892944
1.824611783027649
1.8763388395309448
1.7421766519546509
1.7955280542373657
1.721191167831421
1.7747818231582642
1.7324073314666748
1.6508498191833496
1.7287554740905762
1.7300363779067993
1.6977758407592773
1.6562801599502563
1.7061312198638916
1.7332590818405151
1.757253646850586
1.8243910074234009
1.7929178476333618
1.5414608716964722
1.6750366687774658
1.6614723205566406
1.770839810371399
1.6594958305358887
1.621053695678711
1.6518186330795288
1.647497534751892
1.6116427183151245
1.638241

1.4666593074798584
1.5206233263015747
1.466220498085022
1.4646763801574707
1.4699506759643555
1.4669855833053589
1.600408911705017
1.4923076629638672
1.4784693717956543
1.5127774477005005
1.4361844062805176
1.4592427015304565
1.5684270858764648
1.483363151550293
1.5078599452972412
1.5014818906784058
1.5544250011444092
1.473097562789917
1.525697946548462
1.5643523931503296
1.403715968132019
1.4488904476165771
1.5582484006881714
1.513358473777771
1.4441373348236084
1.4693505764007568
1.443634033203125
1.4791446924209595
1.3890061378479004
1.5683276653289795
1.492783546447754
1.4444479942321777
1.4598727226257324
1.4630756378173828
1.4365925788879395
1.4701720476150513
1.4395010471343994
1.466739296913147
1.4670751094818115
1.4181221723556519
1.527669072151184
1.4381861686706543
1.4933041334152222
1.5082849264144897
1.4854135513305664
1.4904911518096924
1.4204078912734985
1.484108567237854
1.5542057752609253
1.4029921293258667
1.4437259435653687
1.4286317825317383
1.525800108909607
1.5117

In [19]:
h=torch.tensor([9,5,6])
g=modely(h.float())
j = F.softmax(g).tolist()
print(j)

[0.7357112169265747, 0.08136425167322159, 0.024830715730786324, 0.01161021925508976, 0.08660987764596939, 0.03786030784249306, 0.014922617003321648, 0.005698032211512327, 0.0013927971012890339]


C:\Users\soumi\AppData\Local\Temp\ipykernel_14040\2734361591.py:3: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  j = F.softmax(g).tolist()


In [20]:
# import json
# from flask import Flask, request, jsonify, render_template
# from flask_cors import CORS
# import random




# @app.route('/')
# def index():
#     return render_template('index.html', items = "Hello from backend")
#     # return "<h1>Hello, World</h1>"


# @app.route('/calc', methods=['REQUEST'])
# def calc():
#     data = json.loads(request.data)
#     # qns = dict(data['input'])

#     # risk_score = (qns[1])*0.15 + (qns[2])*0.1 + (qns[3])*0.3 + (qns[5])*0.15 + (qns[6])*0.12 + (qns[7])*0.05 + (qns[8])*0.08;
#     # diversity_score = (qns[4])*0.1 + (qns[5])*0.08+ (qns[9])*0.1 + 2/risk_score; 
#     # stability_score = (qns[1])*0.1 + (qns[2])*0.1 + (qns[6])*0.2 + (qns[7])*0.15 + (qns[8])*0.15 + (qns[5])*0.4;
    
#     print(data)   
    
    
#     return jsonify({'output': data})

# app.run(host = '127.0.0.1',port='5000',debug=True)

In [21]:
import json
from flask import Flask, request, jsonify, render_template
from flask_cors import CORS
import random

In [22]:
app = Flask(__name__)
# cors = CORS(app)

In [23]:
@app.route('/index')
def index():
    return "Alive"
    # return "<h1>Hello, World</h1>"


In [24]:
@app.route('/do', methods=['REQUEST'])
def do():
    data = json.loads(request.data)
    print(data)
    qns = (data['calculate'])
    rmax = 4
    smax = 5.25
    dmax = 4

    rout = (qns[0]/rmax)*10
    sout = (qns[1]/smax)*10
    dout = (qns[2]/dmax)*10

    h=torch.tensor([int(rout),int(sout),int(dout)])
    g=modely(h.float())
    j = F.softmax(g).tolist()
    print(j) 
    return jsonify({'output': j}) 

In [25]:
app.run(host = '192.168.197.222',port='5000')

 * Serving Flask app '__main__'
 * Debug mode: off


 * Running on http://192.168.197.222:5000
Press CTRL+C to quit
192.168.197.115 - - [19/Mar/2024 03:23:37] "OPTIONS /do HTTP/1.1" 200 -
192.168.197.115 - - [19/Mar/2024 03:23:37] "OPTIONS /do HTTP/1.1" 200 -
192.168.197.115 - - [19/Mar/2024 03:23:40] "OPTIONS /do HTTP/1.1" 200 -
192.168.197.115 - - [19/Mar/2024 03:23:40] "OPTIONS /do HTTP/1.1" 200 -
192.168.197.115 - - [19/Mar/2024 03:23:41] "OPTIONS /do HTTP/1.1" 200 -
192.168.197.115 - - [19/Mar/2024 03:23:41] "OPTIONS /do HTTP/1.1" 200 -
