In [6]:
import pandas as pd
import torch
import random
import numpy as np
import torch.nn.functional as F
import torch.nn as nn

In [7]:
data = pd.read_csv('portfolio.csv')
print(data)
data = torch.tensor([data["0"],data["1"],data["2"],data["3"],data["4"],data["5"],data["6"],data["7"],data["8"],data["9"],data["10"],data["11"]])
data

     0  1  2     3     4     5     6     7    8     9    10   11
0    3  5  8  0.40  0.20  0.30  0.10  0.00  0.0  0.00  0.00  0.0
1    7  3  6  0.60  0.20  0.00  0.00  0.10  0.1  0.00  0.00  0.0
2    2  7  9  0.20  0.50  0.20  0.10  0.00  0.0  0.00  0.00  0.0
3    6  5  4  0.55  0.15  0.00  0.00  0.15  0.1  0.05  0.00  0.0
4    8  2  3  0.70  0.00  0.00  0.00  0.15  0.0  0.10  0.05  0.0
..  .. .. ..   ...   ...   ...   ...   ...  ...   ...   ...  ...
252  4  2  7  0.35  0.15  0.35  0.15  0.00  0.0  0.00  0.00  0.0
253  8  6  3  0.60  0.10  0.00  0.00  0.15  0.1  0.05  0.00  0.0
254  3  1  9  0.25  0.10  0.50  0.15  0.00  0.0  0.00  0.00  0.0
255  6  8  4  0.50  0.20  0.10  0.00  0.10  0.1  0.00  0.00  0.0
256  9  3  6  0.65  0.05  0.00  0.20  0.05  0.0  0.00  0.05  0.0

[257 rows x 12 columns]


tensor([[3.0000, 7.0000, 2.0000,  ..., 3.0000, 6.0000, 9.0000],
        [5.0000, 3.0000, 7.0000,  ..., 1.0000, 8.0000, 3.0000],
        [8.0000, 6.0000, 9.0000,  ..., 9.0000, 4.0000, 6.0000],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0500],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],
       dtype=torch.float64)

In [8]:
X = data[0:3]
Y = data[3:12]

In [9]:
len(X[0])

257

In [10]:
X,Y

(tensor([[3., 7., 2., 6., 8., 4., 5., 7., 3., 6., 8., 2., 5., 7., 4., 6., 8., 3.,
          5., 7., 4., 6., 8., 2., 5., 7., 3., 6., 8., 4., 5., 7., 3., 6., 8., 2.,
          5., 7., 4., 6., 8., 3., 5., 7., 4., 6., 8., 2., 5., 7., 3., 6., 8., 4.,
          5., 7., 3., 6., 8., 2., 5., 7., 4., 6., 8., 3., 5., 7., 4., 6., 8., 2.,
          5., 7., 4., 6., 8., 3., 5., 7., 4., 6., 8., 2., 5., 7., 4., 6., 8., 3.,
          5., 7., 4., 6., 8., 2., 5., 7., 4., 6., 9., 5., 7., 3., 6., 8., 2., 4.,
          6., 8., 1., 5., 7., 4., 6., 9., 2., 5., 7., 3., 8., 4., 6., 9., 1., 5.,
          7., 4., 6., 8., 2., 5., 7., 3., 6., 9., 1., 4., 7., 5., 8., 2., 6., 9.,
          3., 5., 7., 4., 8., 1., 6., 9., 2., 5., 7., 3., 8., 4., 6., 9., 1., 5.,
          7., 4., 6., 8., 3., 5., 7., 4., 6., 9., 2., 5., 7., 3., 8., 4., 6., 9.,
          5., 7., 3., 6., 8., 2., 4., 7., 5., 9., 1., 6., 8., 4., 7., 3., 5., 8.,
          1., 6., 9., 2., 4., 7., 5., 8., 3., 6., 9., 1., 4., 7., 5., 8., 2., 6.,
          9., 3.

In [11]:
Y.shape,X.shape

(torch.Size([9, 257]), torch.Size([3, 257]))

In [12]:
Xt=[]
Yt=[]
for i in range(len(X[0])):
    tempx = ([X[0][i],X[1][i],X[2][i]])
    tempy = ([Y[0][i],Y[1][i],Y[2][i],Y[3][i],Y[4][i],Y[5][i],Y[6][i],Y[7][i],Y[8][i]])
    Xt.append(tempx)
    Yt.append(tempy)
Xt=torch.tensor(Xt)
Yt=torch.tensor(Yt)
    

In [13]:
Xt = Xt.float()
Yt=Yt.float()

In [14]:
Xt[0],Yt[0]

(tensor([3., 5., 8.]),
 tensor([0.4000, 0.2000, 0.3000, 0.1000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]))

In [15]:
xtrain = Xt[:int(0.9*len(Xt))]
ytrain = Yt[:int(0.9*len(Yt))]
xtest = Xt[int(0.9*len(Xt)):]
ytest = Yt[int(0.9*len(Yt)):]

In [16]:
ex_len = 3
n_ol = 9

bat_sz = 4
n_fl = 64
n_ml = 64
epoch = 10

head_sz = 16

In [17]:
class Reshaper(nn.Module):
    def __init__(self,n):
        self.n = n
        super(Reshaper, self).__init__()

    def forward(self, x):
        B, T, C = x.shape
        x = x.view(B, T//self.n, C*self.n)
        if x.shape[1] == 1:
            x = x.squeeze(1)
        self.out = x
        return self.out

In [18]:
modely = nn.Sequential(
    nn.Embedding(ex_len,n_fl),     #  Gets the input ([10000,8,16])
    Reshaper(2),  # becomes [10000,4,32]  # [inp_sz,blk_sz//2,emb_sz*2]
    nn.Linear(n_fl*2,n_fl),       # takes [32,200]  becomes [10000,4,200]
    nn.Tanh(),
    Reshaper(2),  # becomes [10000,2,400]   # [inp_sz,blk_sz//4,n_fl*2]
    nn.Linear(n_fl*2,n_fl),    # becomes  [10000,2,200]
    nn.Tanh(),
    Reshaper(2),  # becomes [10000,400]  # [inp_sz,n_fl*2]
    nn.Linear(n_fl*2,n_ol),    # become [400,voc_sz]
    nn.Softmax(),
)

In [19]:
optimizer = torch.optim.SGD(modely.parameters(), lr=0.001)

In [20]:
# attention
@torch.no_grad()
def self_attention(x):  

    B,T,C = x.shape
    # B = 4  # block size
    # T = 8  # token (number of tokens in one example)
    # C = 32 # embedding space vector of the each one token
    # x = torch.randn(B,T,C) # example sequence
    # x -> this is how our one batch should look like here 


    # head_sz = 32# this is the splits we do of each token seqence to parellelize the sequence gen

    key = nn.Linear(C,head_sz,bias=False) # this is to make to complexities truly match  
    query =  nn.Linear(C,head_sz,bias=False) 
    value =  nn.Linear(C,head_sz,bias=False) 
    k = key(x)  # [B,T,head_sz]
    q = query(x)  # [B,T,head_sz]
    # this is -- x @ key --  then 
    # upcoming wei is the main token to token connection matrix
    wei = q @ k.transpose(-2,-1)
    # wei[0]  # TxT

    tril = torch.tril(torch.ones(T, T))  # makes a lower triangular matrix of TxT
    wei = wei.masked_fill(tril == 0, float('-inf'))
    wei = F.softmax(wei, dim=-1)

    v = value(x)
    out = wei @ v
    # out[0].shape
    return out

# basically this is what makes up the new and improved input to the neural net

In [21]:
def embed(dim,sqz):
    a="sdjnf"

modely = nn.Sequential(

    nn.Linear(ex_len,n_fl),
    nn.ReLU(),
    nn.Linear(n_fl,n_ml), 
    # nn.Tanh(),
    nn.Linear(n_ml,n_ol),
    # nn.Softmax(),
)

ix = (torch.randperm(len(xtrain)-bat_sz))
optimizer = torch.optim.SGD(modely.parameters(), lr=0.001)

X_Train = torch.zeros([64,16,16])

In [22]:
def accuracy():
    k,d=len(xtest),len(xtest)
    for n in range(len(xtest)):
        omt = ((modely(xtest[n]))).tolist()
        # print(omt.index(max(omt)),ytest[n].item())

        k -= (omt.index(max(omt))==ytest[n].item())
    accu = (((d-k)/d) *100)
    return("Accuracy = " + str(accu))

In [23]:
for e in range(epoch):
    for i in ix:
        xt = xtrain[i:i+bat_sz]
        yt = ytrain[i:i+bat_sz]
        X_train = xt.view([bat_sz,ex_len]) #[4,784]
        Y_train = yt
        # print(X_train,Y_train)
        # break
        
        X_Train = X_Train +self_attention(X_Train)
        
        
        t = modely(X_train)
        loss = F.cross_entropy(t,Y_train) 
        optimizer.zero_grad()

        loss.backward()  # ------------
        optimizer.step()
        
        print(loss.item())
    # print(accuracy())
    if(e == int(0.8*epoch)):
        optimize = torch.optim.SGD(modely.parameters(), lr=0.0001)

2.3497378826141357
2.3176233768463135
2.265876293182373
2.306464433670044
2.2145888805389404
2.1606483459472656
2.1426756381988525
2.152340888977051
2.1680150032043457
2.0482165813446045
2.1229569911956787
2.0249276161193848
2.0781068801879883
2.006100654602051
1.9099576473236084
1.845393419265747
1.9231152534484863
1.93113374710083
1.9112365245819092
1.9101768732070923
1.882789134979248
1.9673130512237549
1.8848117589950562
1.9090592861175537
1.8167325258255005
1.8961564302444458
1.8743538856506348
1.8250367641448975
1.8468018770217896
1.8489017486572266
1.8187271356582642
1.6975657939910889
1.8003454208374023
1.8117436170578003
1.729683518409729
1.7451859712600708
1.743950605392456
1.8162134885787964
1.8251817226409912
1.7684013843536377
1.759057641029358
1.7416287660598755
1.771670937538147
1.729378342628479
1.6947110891342163
1.8164618015289307
1.7905304431915283
1.7581701278686523
1.7120046615600586
1.7928786277770996
1.6541773080825806
1.7178130149841309
1.6541508436203003
1.7125

In [24]:
h=torch.tensor([9,5,6])
g=modely(h.float())
j = F.softmax(g).tolist()
print(j)

[0.7110700011253357, 0.08834732323884964, 0.03320370987057686, 0.015240446664392948, 0.08360584080219269, 0.04505513235926628, 0.017669619992375374, 0.0042341165244579315, 0.001573701505549252]


C:\Users\soumi\AppData\Local\Temp\ipykernel_20500\2734361591.py:3: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  j = F.softmax(g).tolist()


In [ ]:
import json
from flask import Flask, request, jsonify, render_template
from flask_cors import CORS
import random




@app.route('/')
def index():
    return render_template('index.html', items = "Hello from backend")
    # return "<h1>Hello, World</h1>"


@app.route('/calc', methods=['REQUEST'])
def calc():
    data = json.loads(request.data)
    # qns = dict(data['input'])

    # risk_score = (qns[1])*0.15 + (qns[2])*0.1 + (qns[3])*0.3 + (qns[5])*0.15 + (qns[6])*0.12 + (qns[7])*0.05 + (qns[8])*0.08;
    # diversity_score = (qns[4])*0.1 + (qns[5])*0.08+ (qns[9])*0.1 + 2/risk_score; 
    # stability_score = (qns[1])*0.1 + (qns[2])*0.1 + (qns[6])*0.2 + (qns[7])*0.15 + (qns[8])*0.15 + (qns[5])*0.4;
    
    print(data)   
    
    
    return jsonify({'output': data})

app.run(host = '127.0.0.1',port='5000',debug=True)

In [25]:
import json
from flask import Flask, request, jsonify, render_template
from flask_cors import CORS
import random

In [26]:
app = Flask(__name__)
# cors = CORS(app)

In [27]:
@app.route('/index')
def index():
    return "Alive"
    # return "<h1>Hello, World</h1>"


In [28]:
@app.route('/calc', methods=['REQUEST'])
def calc():
    data = json.loads(request.data)
    # qns = dict(data['input'])
    # rmax = 4
    # smax = 5.25
    # dmax = 4

    # rout = (rsk/rmax)*100
    # sout = (stab/smax)*100
    # dout = (diver/dmax)*100
    # risk_score = (qns[1])*0.15 + (qns[2])*0.1 + (qns[3])*0.3 + (qns[5])*0.15 + (qns[6])*0.12 + (qns[7])*0.05 + (qns[8])*0.08;
    # diversity_score = (qns[4])*0.1 + (qns[5])*0.08+ (qns[9])*0.1 + 2/risk_score; 
    # stability_score = (qns[1])*0.1 + (qns[2])*0.1 + (qns[6])*0.2 + (qns[7])*0.15 + (qns[8])*0.15 + (qns[5])*0.4;
    
    print(data)  
    return jsonify({'output': data}) 

In [30]:
app.run(host = '192.168.197.222',port='5000')

 * Serving Flask app '__main__'
 * Debug mode: off


 * Running on http://192.168.197.222:5000
Press CTRL+C to quit
